name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]
    paths: '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        run: |
          find . -type f -name "*.sh" \
            | while read -r TARGET; do \
                shellcheck "${TARGET}" ; \
              done
